# lightning.pytorch==2.0.1.post0
seed_everything: 42
trainer:
  default_root_dir: runs/
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: 32-true
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: mlp-swag
      save_dir: runs/
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: lab-2-question-answering
      log_model: true
      experiment: null
      prefix: ''
      checkpoint_name: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: accuracy/validation
        verbose: false
        save_top_k: 1
        save_last: true
        save_weights_only: false
        mode: max
        every_n_train_steps: null
        filename: null
  fast_dev_run: false
  max_epochs: 20
  overfit_batches: 0.0
  check_val_every_n_epoch: 1
  accumulate_grad_batches: 1
  reload_dataloaders_every_n_epochs: 0
data:
  class_path: data_loader.FeatureDataModule
  init_args:
    root_dir: ./data/
    dataset: swag
    batch_size: 32
    num_workers: 4
    pin_memory: true
model:
  num_choices: 4
  input_size: 768
  hidden_size: 256
  criterion: MultiMarginLoss
  learning_rate: 1.0e-05
  adam_epsilon: 1.0e-08
  warmup_steps: 0
  weight_decay: 0.0
ckpt_path: null
