from data_loader.race_datamodule import RACEDataModule
from data_loader.swag_datamodule import SWAGDataModule
from data_loader.feature_datamodule import FeatureDataModule
from data_loader.tweet_eval_datamodule import TweetEvalDataModule